config/routes.rb
Rails.application.routes.draw do
  root "artists#index"
  resources :artists
  resources :albums
  resources :songs do 
    resources :ratings 
  end
  get "/genre_sort", to: "albums#genre_sort"
  get "/year_sort", to: "albums#year_sort"

end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :artist, class_name: "Artist", foreign_key: "artist_id"
    has_many :songs, dependent: :destroy 
    validates :title, presence: true 
    validates :genre, presence: true 
    validates :release, presence: true 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums, dependent: :destroy

    validates :name, presence: true 
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :song, class_name: "Song", foreign_key: "song_id"
    validates :evaluation, presence: true, numericality: { less_than_or_equal_to: 5, greater_than_or_equal_to: 0 }
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :album, inverse_of: :songs, class_name: "Album", foreign_key: "album_id"
    has_one :rating, dependent: :destroy
    validates :subject, presence: true 
    validates :rhythm, presence: true 
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show 
    @album = Album.find(params[:id])
  end 

  def new 
    @album = Album.new
  end 

  def create
    @album = Album.new(album_params)

    if @album.save 
      flash[:success] = "New Album successfully created!"
      redirect_to album_path(@album)
    else 
      flash.now[:error] = "New Album creation failed!"
      render :new 
    end  
  end 

  def edit 
    @album = Album.find(params[:id])
  end 

  def update 
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album 
    else 
      render :edit 
    end 
  end 

  def destroy 
    @album = Artist.find(params[:id]).albums.find(params[:id])
    @album.destroy

    redirect_to root_path
  end 

  def genre_sort
    if params[:search_by_genre] && params[:search_by_genre] != ""
      @songs = Song.joins(:album).where("genre LIKE ?", params[:search_by_genre]).joins(:rating).order("ratings.evaluation DESC")
    end  
  end 

  def year_sort
    if params[:search_by_year] && params[:search_by_year] != ""
      @songs = Song.joins(:album).where("release LIKE ?", params[:search_by_year])
    end  
  end 

  private 
    def album_params 
      params.require(:album).permit(:title, :genre, :release, :album_id, :artist_id)
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show 
    @artist = Artist.find(params[:id])
  end 

  def new 
    @artist = Artist.new 
  end 

  def create 
    @artist = Artist.new(artist_params)

    if @artist.save 
      redirect_to @artist
    else 
      render :new 
    end 
  end 

  def edit 
    @artist = Artist.find(params[:id])
  end 

  def update 
    @artist = Artist.find(params[:id])

    if @artist.update(artist_params)
      redirect_to @artist 
    else 
      render :edit 
    end 
  end 

  def destroy 
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to root_path
  end 

  private 
    def artist_params 
      params.require(:artist).permit(:name, album_ids:[], song_ids:[])
    end 
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create 
    @song = Song.find(params[:song_id])
    @rating = @song.create_rating!(rating_params)
    
    if @rating.save
      flash[:success] = "New Rating successfully created!"
      redirect_to song_path(@song)
    else 
      flash.now[:error] = "New Rating creation failed!"
    end 
  end 

  private 
    def rating_params 
      params.require(:rating).permit(:evaluation)
    end 
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show 
    @song = Song.find(params[:id])
  end 

  def new 
    @song = Song.new 
  end 

  def create 
    @song = Song.new(song_params)

    if @song.save 
      flash[:success] = "New Song successfully created!"
      redirect_to song_path(@song)
    else 
      flash.now[:error] = "New Song creation failed!"
      render :new 
    end  

  end 

  def edit 
    @song = Song.find(params[:id])
  end 

  def update 
    @song = Song.find(params[:id])

    if  @song.update(song_params)
        redirect_to @song
    else 
      render :edit 
    end 
  end 

  def destroy 
    @song = Song.find(params[:id])
    @song.destroy

    redirect_to root_path
  end 

  private 
    def song_params 
      params.require(:song).permit(:subject, :rhythm, :album_id)
    end 
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.slim
div 
    =form_with model: @album do |form|

        =form.label :Artist
        =form.select :artist_id, Artist.all.collect { |artist| [artist.name, artist.id] }, include_blank: true

        br 

        =form.label :Name 
        =form.text_field :title
            -@album.errors.full_messages_for(:title).each do |message|
                =message 

        br

        =form.label :Genre 
        =form.text_field :genre
            -@album.errors.full_messages_for(:genre).each do |message|
                =message 

        br

        =form.label :Year 
        =form.text_field :release
            -@album.errors.full_messages_for(:release).each do |message|
                =message 

        br

        =form.submit
 

app/views/albums/edit.html.slim
h1 
    | Edit Album 

=render "form", album: @album

app/views/albums/genre_sort.html.slim
h1 
    |Sort by genre

= form_tag "/genre_sort", method: "GET" do 
    =label_tag :search_by_genre
    = text_field_tag :search_by_genre, params[:search_by_genre]
    = submit_tag "Search"
h1 
    |Search Results 

-if @songs.present? 
    -@songs.each do |song|
        ul
            =song.subject 
            |,
            =song.rhythm 
            |,
            =song.album.title
            |, 
            =song.album.release 
            |,
            =song.album.artist.name
            br
    br 
-else 
    |No results found
    br 
br 

=link_to "Home", root_path 

app/views/albums/new.html.slim
h1 
    | Add new Album

=render "form", album: @album

app/views/albums/show.html.slim
h1 
    =@album.artist.name

h1 
    = @album.title
    |,  
    = @album.genre
    |,  
    = @album.release
br 

h2
    -@album.songs.each do |song|
        ul 
            =link_to song.subject, song 
            |, 
            = song.rhythm

=link_to "Add Song", new_song_path(@album)
br 
=link_to "Sort song by year", year_sort_path
br
=link_to "Sort song by genre", genre_sort_path
br
=link_to "Edit Album", edit_album_path(@album)
br 
=link_to "Delete this Album", album_path(@album),
                    method: :delete,
                    data: { confirm: "Are you sure?"}
br 
=link_to "Home", root_path 

app/views/albums/year_sort.html.slim
h1 
    |Sort by year

= form_tag "/year_sort", method: "GET" do 
    =label_tag :search_by_year
    = text_field_tag :search_by_year, params[:search_by_year]
    = submit_tag "Search"
h1 
    |Search Results 

-if @songs.present? 
    -@songs.each do |song|
        ul
            =song.subject 
            |,
            =song.rhythm 
            |,
            =song.album.title
            |, 
            =song.album.release 
            |,
            =song.album.artist.name
            br
    br 
-else 
    |No results found
    br 
br 

=link_to "Home", root_path 

app/views/artists/_form.html.slim
div 
    =form_with model: @artist do |form|
        =form.label :Name 
        =form.text_field :name
        -@artist.errors.full_messages_for(:name).each do |message|
            =message 

        =form.submit
 

app/views/artists/edit.html.slim
h1 
    | Edit Artist

=render "form", artist: @artist

app/views/artists/index.html.slim
h1 
    | List of Artists 

-@artists.each do |artist|
    ul 
        =link_to artist.name, artist
br 

=link_to "Add Artist", new_artist_path 

app/views/artists/new.html.slim
h1 
    | Add new Artist

=render "form", artist: @artist

app/views/artists/show.html.slim
h1 
    =@artist.name

br 

h2  
    | Albums
    br 

div 
    -@artist.albums.each do |album|
        ul 
            =link_to album.title, album_path(album)
            |, 
            =album.genre 
            |, 
            =album.release
            br 

br 
=link_to "Add Album", new_album_path(@artist, :artist_id)
br 
=link_to "Edit Artist", edit_artist_path(@artist)
br 
=link_to "Delete this Artist", artist_path(@artist),
                    method: :delete,
                    data: { confirm: "Are you sure?"}
br 
=link_to "Home", root_path 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ratings/_form.html.slim
div 
    =form_with model: [@song, @song.build_rating] do |form|
        =form.label :rating 
        =form.text_field :evaluation
        - @song.rating.errors.full_messages_for(:evaluation).each do |message|
            div 
                = message 

        =form.submit
 

app/views/songs/_form.html.slim
div 
    =form_with model: @song do |form|

        =form.label :Album
        =form.select :album_id, Album.all.collect { |album| [album.title, album.id] }, include_blank: true 

        =form.label :title 
        =form.text_field :subject
        -@song.errors.full_messages_for(:subject).each do |message|
            =message 

        =form.label :Duration 
        =form.text_field :rhythm
        -@song.errors.full_messages_for(:rhythm).each do |message|
            =message 

        =form.submit
 

app/views/songs/edit.html.slim
h1 
    | Edit Song

=render "form", song: @song

app/views/songs/new.html.slim
h1 
    | Add new Song 

=render "form", song: @song

app/views/songs/show.html.slim
h1 
    =@song.album.title

h2
    =@song.subject
    |, 
    =@song.rhythm

h3 
    -if @song.rating.present?
        | Rating: 
        = @song.rating.evaluation 
        |/5
    -else 
        |Set Rating for song out of 5
        = render "ratings/form"

=link_to "Edit Song", edit_song_path(@song)
br 
=link_to "Delete this Song", song_path(@song),
                    method: :delete,
                    data: { confirm: "Are you sure?"}
br
=link_to "Home", root_path 